export enum ClassLevel {
  CLASS_LEVEL_1 = "CLASS_LEVEL_1",
  CLASS_LEVEL_2 = "CLASS_LEVEL_2",
  CLASS_LEVEL_3 = "CLASS_LEVEL_3",
  CLASS_LEVEL_4 = "CLASS_LEVEL_4",
  CLASS_LEVEL_5 = "CLASS_LEVEL_5",
}
